### ISSUE TITLE
DPAD not detected

### ISSUE THREAD

**Issue by ghost** [m45t3r/BootCtr#1]
The DPAD is not detected on my 2DS.

System Info:
2DS 9.2.0-20 with autoboot menuhax

**Comment by ghost** [comment]
This still isn't fixed. DPAD still is not detected, and instead falls through to the default entry.

**Comment by ghost** [comment]
The same applies to CPAD.

**Comment by thiagokokada** [comment]
Well, it works for me. Is this still a problem?

**Comment by ghost** [comment]
Nah. It's fixed now.
